-- Creazione tabella CATEGORY
CREATE TABLE CATEGORY (
    CategoryID SERIAL PRIMARY KEY,
    TrainCategory VARCHAR(50) NOT NULL UNIQUE,
    PriorityValue INT NOT NULL
    
);

-- Creazione tabella TRAINS
CREATE TABLE TRAINS (
    TrainID SERIAL PRIMARY KEY,
    Destination VARCHAR(100) NOT NULL,
    Vagons INT CHECK (Vagons BETWEEN 5 AND 15),
    TimeDelay INT NOT NULL,
    DepartureTrain TIMESTAMP NOT NULL,
    ArrivalTrain TIMESTAMP NOT NULL
    CategoryID INT REFERENCES CATEGORY(CategoryID) ON DELETE SET NULL
);

-- Creazione tabella RAIL
CREATE TABLE RAIL (
    RailID SERIAL PRIMARY KEY,
    RailName VARCHAR(50) NOT NULL
);

-- Creazione tabella SEGMENTRAIL
CREATE TABLE SEGMENTRAIL (
    SegmentRailID SERIAL PRIMARY KEY,
    RailID INT REFERENCES RAIL(RailID) ON DELETE SET NULL,
    SegmentName VARCHAR(50) NOT NULL UNIQUE,
    IsOccupied BOOLEAN DEFAULT FALSE
);

-- Creazione tabella CROSSROADS
CREATE TABLE CROSSROADS (
    CrossroadID SERIAL PRIMARY KEY,
    SegmentTrait1 INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    SegmentTrait2 INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Changelane BOOLEAN DEFAULT TRUE,
    IsOccupied BOOLEAN DEFAULT FALSE
);

-- Creazione tabella STOPLIGHT
CREATE TABLE STOPLIGHT (
    StoplightID SERIAL PRIMARY KEY,
    SegmentRailID INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Redlight BOOLEAN DEFAULT FALSE
);

-- Creazione tabella WAGONS
CREATE TABLE WAGONS (
    WagonID SERIAL PRIMARY KEY,
    TrainID INT REFERENCES TRAINS(TrainID) ON DELETE SET NULL,
    WagonsSegment INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Capacity INT NOT NULL
);


--Per Sql server questo è lo script

-- Creazione tabella CATEGORY
CREATE TABLE CATEGORY (
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    TrainCategory VARCHAR(50) NOT NULL UNIQUE,
    PriorityValue INT NOT NULL
);

-- Creazione tabella TRAINS
CREATE TABLE TRAINS (
    TrainID INT IDENTITY(1,1) PRIMARY KEY,
    Destination VARCHAR(100) NOT NULL,
    Vagons INT CHECK (Vagons BETWEEN 5 AND 15),
    TimeDelay INT NOT NULL,
    DepartureTrain DATETIME2 NOT NULL,
    ArrivalTrain DATETIME2 NOT NULL,
    CategoryID INT NULL,
    CONSTRAINT FK_TRAINS_CATEGORY 
        FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE SET NULL
);

-- Creazione tabella RAIL
CREATE TABLE RAIL (
    RailID INT IDENTITY(1,1) PRIMARY KEY,
    RailName VARCHAR(50) NOT NULL
);

-- Creazione tabella SEGMENTRAIL
CREATE TABLE SEGMENTRAIL (
    SegmentRailID INT IDENTITY(1,1) PRIMARY KEY,
    RailID INT NULL,
    SegmentName VARCHAR(50) NOT NULL UNIQUE,
    IsOccupied BIT DEFAULT 0,
    CONSTRAINT FK_SEGMENTRAIL_RAIL
        FOREIGN KEY (RailID) REFERENCES RAIL(RailID) ON DELETE SET NULL
);

-- Creazione tabella CROSSROADS senza cascata
CREATE TABLE CROSSROADS (
    CrossroadID INT IDENTITY(1,1) PRIMARY KEY,
    SegmentTrait1 INT NULL,
    SegmentTrait2 INT NULL,
    Changelane BIT DEFAULT 1,
    IsOccupied BIT DEFAULT 0,
    CONSTRAINT FK_CROSSROADS_SEG1
        FOREIGN KEY (SegmentTrait1) REFERENCES SEGMENTRAIL(SegmentRailID),
    CONSTRAINT FK_CROSSROADS_SEG2
        FOREIGN KEY (SegmentTrait2) REFERENCES SEGMENTRAIL(SegmentRailID)
);

-- Creazione tabella STOPLIGHT
CREATE TABLE STOPLIGHT (
    StoplightID INT IDENTITY(1,1) PRIMARY KEY,
    SegmentRailID INT NULL,
    Redlight BIT DEFAULT 0,
    CONSTRAINT FK_STOPLIGHT_SEGMENTRAIL
        FOREIGN KEY (SegmentRailID) REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL
);

-- Creazione tabella WAGONS
CREATE TABLE WAGONS (
    WagonID INT IDENTITY(1,1) PRIMARY KEY,
    TrainID INT NULL,
    WagonsSegment INT NULL,
    Capacity INT NOT NULL,
    CONSTRAINT FK_WAGONS_TRAINS
        FOREIGN KEY (TrainID) REFERENCES TRAINS(TrainID) ON DELETE SET NULL,
    CONSTRAINT FK_WAGONS_SEGMENTRAIL
        FOREIGN KEY (WagonsSegment) REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL
);

