

-- Creazione tabella CATEGORY
CREATE TABLE CATEGORY (
    CategoryID SERIAL PRIMARY KEY,
    TrainCategory VARCHAR(50) NOT NULL UNIQUE,
    PriorityValue INT NOT NULL,
    TimeDelay INT NOT NULL,
    DepartureTrain TIMESTAMP NOT NULL,
    ArrivalTrain TIMESTAMP NOT NULL
);

-- Creazione tabella TRAINS
CREATE TABLE TRAINS (
    TrainID SERIAL PRIMARY KEY,
    Destination VARCHAR(100) NOT NULL,
    Vagons INT CHECK (Vagons BETWEEN 5 AND 15),
    CategoryID INT REFERENCES CATEGORY(CategoryID) ON DELETE SET NULL
);

-- Creazione tabella RAIL
CREATE TABLE RAIL (
    RailID SERIAL PRIMARY KEY,
    RailName VARCHAR(50) NOT NULL
);

-- Creazione tabella SEGMENTRAIL
CREATE TABLE SEGMENTRAIL (
    SegmentRailID SERIAL PRIMARY KEY,
    RailID INT REFERENCES RAIL(RailID) ON DELETE SET NULL,
    SegmentName VARCHAR(50) NOT NULL UNIQUE,
    IsOccupied BOOLEAN DEFAULT FALSE
);

-- Creazione tabella CROSSROADS
CREATE TABLE CROSSROADS (
    CrossroadID SERIAL PRIMARY KEY,
    SegmentTrait1 INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    SegmentTrait2 INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Changelane BOOLEAN DEFAULT TRUE,
    IsOccupied BOOLEAN DEFAULT FALSE
);

-- Creazione tabella STOPLIGHT
CREATE TABLE STOPLIGHT (
    StoplightID SERIAL PRIMARY KEY,
    SegmentRailID INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Redlight BOOLEAN DEFAULT FALSE
);

-- Creazione tabella WAGONS
CREATE TABLE WAGONS (
    WagonID SERIAL PRIMARY KEY,
    TrainID INT REFERENCES TRAINS(TrainID) ON DELETE SET NULL,
    WagonsSegment INT REFERENCES SEGMENTRAIL(SegmentRailID) ON DELETE SET NULL,
    Capacity INT NOT NULL
);
